spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:4399/pasteme
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    sqlite:
      jdbc-url: jdbc:sqlite:db.sqlite
      driver-class-name: org.sqlite.JDBC

